const express = require('express');
const router = express.Router();
const friendController = require('../controllers/friendController');
const { authRequest,  validateUser} = require('../middleware/validateRequest');

router.get('/get-user-friends', [authRequest, validateUser], friendController.getUserFriends);
router.get('/get-pending-requests', [authRequest, validateUser], friendController.getPendingRequests);
router.post('/cancel-request', [authRequest, validateUser], friendController.cancelRequest);
router.put('/accept-request', [authRequest, validateUser], friendController.acceptRequest);

module.exports = router;

// curl -X GET http://localhost:3000/api/friends/get-user-friends \
//   -H "Content-Type: application/json" \
//   -H "Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtEWVFlT095ZlJKdmlBS20tTG4zZzNxcEpxZTEtSjB3OFV4ZlpNRUtDbHcifQ.eyJzaWQiOiJjbWpvZXpiN2wwMDh4am0wYzdmZWxiMXNzIiwiaXNzIjoicHJpdnkuaW8iLCJpYXQiOjE3NjY4NDY4MjQsImF1ZCI6ImNtamJia3pwbDAxcTRsZDBjaHc0enUxeHkiLCJzdWIiOiJkaWQ6cHJpdnk6Y21qY3R2ZHIwMDBpaGxiMGNwNWJoZDMxdCIsImV4cCI6MTc2Njg1MDQyNH0.Q7zX0UwkFW_jmGNPQ_CyokOoz7VDgpmq7RGipx7t1rb-N4ip-8wMnSGDSawXWCXbaerlveSm0bFBc3azH3SUFg" \
//   -H "privy-id-token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtEWVFlT095ZlJKdmlBS20tTG4zZzNxcEpxZTEtSjB3OFV4ZlpNRUtDbHcifQ.eyJjciI6IjE3NjYxNDYyNDEiLCJsaW5rZWRfYWNjb3VudHMiOiJbe1widHlwZVwiOlwiZW1haWxcIixcImFkZHJlc3NcIjpcImV0aW1wYXVsMjJAZ21haWwuY29tXCIsXCJsdlwiOjE3NjY4NDY4MjR9LHtcImlkXCI6XCJtMTRsOWhlc2VuN3R0OHJrYXZ1aTQzcDJcIixcInR5cGVcIjpcIndhbGxldFwiLFwiYWRkcmVzc1wiOlwiMHg3YzAzZDg5Zjk2NTU3NTc4MTA2ZmE4NWFmMjU4NzdkMmI5ZjdkOTQxNzNiNDY4NWU5YjdkNjQ4MmRjOWQxMDE0XCIsXCJjaGFpbl90eXBlXCI6XCJhcHRvc1wiLFwid2FsbGV0X2NsaWVudF90eXBlXCI6XCJwcml2eVwiLFwibHZcIjoxNzY2MTQ2MjQyfSx7XCJpZFwiOlwiYTExYXJidHNicHJqZDVicXhhNm15cTd4XCIsXCJ0eXBlXCI6XCJ3YWxsZXRcIixcImFkZHJlc3NcIjpcIjdyQlNzblZhdDltZlBFY3VrZWhXcEFmc0o5eGlMdWJrcEF3YXhZdXVWNXhvXCIsXCJjaGFpbl90eXBlXCI6XCJzb2xhbmFcIixcIndhbGxldF9jbGllbnRfdHlwZVwiOlwicHJpdnlcIixcImx2XCI6MTc2Njc1ODk0Nn0se1wiaWRcIjpcInVra2xjYjZqZjB1NGVhOWl2MWpwdXBpd1wiLFwidHlwZVwiOlwid2FsbGV0XCIsXCJhZGRyZXNzXCI6XCIweDM1Y2YwQkMzNThiQTU5MDZGQzQyMzdBNTNlMTg0OTIwRGY5Y2Q0MjBcIixcImNoYWluX3R5cGVcIjpcImV0aGVyZXVtXCIsXCJ3YWxsZXRfY2xpZW50X3R5cGVcIjpcInByaXZ5XCIsXCJsdlwiOjE3NjY3NTg5NTB9XSIsImlzcyI6InByaXZ5LmlvIiwiaWF0IjoxNzY2ODQ2ODI1LCJhdWQiOiJjbWpiYmt6cGwwMXE0bGQwY2h3NHp1MXh5Iiwic3ViIjoiZGlkOnByaXZ5OmNtamN0dmRyMDAwaWhsYjBjcDViaGQzMXQiLCJleHAiOjE3NjY4NTA0MjV9.xxmk8V9T-u1-FSShQKW2M6U9BNmvLoqsGRGrUMRN7eTbdG_rpgGLv2NAClUkQbZ7YMpfOIFxQZdHDeEXeEnqXg" \
//   -d '{}'